<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="ErrorOr"/>
    <PackageReference Include="Mapster"/>

    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks\BuildingBlocks.csproj"/>
    <ProjectReference Include="..\Catalog.Domain\Catalog.Domain.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Products\CreateProduct\"/>
  </ItemGroup>
</Project>
