<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    <PackageReference Include="OpenTelemetry.Exporter.Console"/>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting"/>
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore"/>
    <PackageReference Include="Serilog"/>
    <PackageReference Include="Serilog.AspNetCore"/>
    <PackageReference Include="Serilog.Enrichers.Environment"/>
    <PackageReference Include="Serilog.Enrichers.OpenTelemetry"/>
    <PackageReference Include="Serilog.Enrichers.Thread"/>
    <PackageReference Include="Serilog.Extensions.Logging"/>
    <PackageReference Include="Serilog.Sinks.Console"/>
    <PackageReference Include="Serilog.Sinks.Grafana.Loki"/>
    <PackageReference Include="Magick.NET.Core"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Configurations\"/>
    <Folder Include="Persistence\Constants\"/>
    <Folder Include="Persistence\Repositories\"/>
  </ItemGroup>

</Project>
