services:

  catalog-api:
    build:
      context: ../../src/Services/Catalog

    environment:
      ASPNETCORE_ENVIRONMENT: Development

    ports:
      - "5001:8080"

    volumes:
      - ../../src/Services/Catalog:/src
