services:
  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  azurite:
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  catalog-db:
    ports:
      - "5432:5432"

  identity-db:
    ports:
      - "5433:5433"
