<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks\BuildingBlocks.csproj"/>
    <ProjectReference Include="..\Identity.Application\Identity.Application.csproj"/>
    <ProjectReference Include="..\Identity.Domain\Identity.Domain.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET.Core"/>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google"/>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces"/>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild"/>
    <PackageReference Include="Npgsql.OpenTelemetry"/>
    <PackageReference Include="OpenTelemetry.Exporter.Console"/>
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"/>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting"/>
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore"/>
    <PackageReference Include="Serilog"/>
    <PackageReference Include="Serilog.AspNetCore"/>
    <PackageReference Include="Serilog.Enrichers.Environment"/>
    <PackageReference Include="Serilog.Enrichers.OpenTelemetry"/>
    <PackageReference Include="Serilog.Enrichers.Thread"/>
    <PackageReference Include="Serilog.Extensions.Logging"/>
    <PackageReference Include="Serilog.Sinks.Console"/>
    <PackageReference Include="Serilog.Sinks.Grafana.Loki"/>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt"/>
  </ItemGroup>

</Project>
