<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions"/>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="Microsoft.Playwright"/>
    <PackageReference Include="Moq"/>
    <PackageReference Include="Testcontainers.PostgreSql"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\BuildingBlocks\BuildingBlocks.csproj"/>
    <ProjectReference Include="..\Services\Identity.API\Identity.API.csproj"/>
    <ProjectReference Include="..\Services\Identity.Application\Identity.Application.csproj"/>
    <ProjectReference Include="..\Services\Identity.Domain\Identity.Domain.csproj"/>
    <ProjectReference Include="..\Services\Identity.Infrastructure\Identity.Infrastructure.csproj"/>
  </ItemGroup>

</Project>
