<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Cloudmart.Identity</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <UserSecretsId>9c3cde7e-99e2-4a8d-9e5e-4b26e80ab938</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    <PackageReference Include="Polly"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces"/>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild"/>
    <PackageReference Include="Carter"/>
    <PackageReference Include="Mapster"/>
    <PackageReference Include="MediatR"/>
    <PackageReference Include="Scalar.AspNetCore"/>
    <PackageReference Include="Scrutor"/>
    <PackageReference Include="Serilog"/>
    <PackageReference Include="Serilog.AspNetCore"/>
    <PackageReference Include="Serilog.Enrichers.Environment"/>
    <PackageReference Include="Serilog.Enrichers.OpenTelemetry"/>
    <PackageReference Include="Serilog.Enrichers.Thread"/>
    <PackageReference Include="Serilog.Extensions.Logging"/>
    <PackageReference Include="Serilog.Sinks.Console"/>
    <PackageReference Include="Serilog.Sinks.Grafana.Loki"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks\BuildingBlocks.csproj"/>
    <ProjectReference Include="..\Identity.Infrastructure\Identity.Infrastructure.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\"/>
  </ItemGroup>
</Project>
