services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
    networks:
      - cloudmart_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_FEATURE_TOGGLES_ENABLE: traceqlEditor
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ../observability/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ../observability/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - cloudmart_net

  tempo:
    image: grafana/tempo:2.7.1
    container_name: tempo
    restart: unless-stopped
    command: -config.file=/etc/tempo/tempo.yml
    volumes:
      - ../observability/tempo/tempo.yml:/etc/tempo/tempo.yml:ro
      - tempo_data:/var/tempo
    depends_on:
      - prometheus
    networks:
      - cloudmart_net

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ../observability/loki/local-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    networks:
      - cloudmart_net

networks:
  cloudmart_net:
    external: true

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  tempo_data:
