version: "3.8"

services:
  azurite:
    container_name: azurite
    platform: linux/amd64
    restart: unless-stopped
    command: >
      azurite
      --skipApiVersionCheck
      --blobHost 0.0.0.0
      --queueHost 0.0.0.0
      --tableHost 0.0.0.0
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
    networks:
      - cloudmart_net
    volumes:
      - azurite_data:/data
  service_bus_emulator:
    container_name: service_bus_emulator
    platform: linux/amd64
    ports:
      - "5672:5672"
  redis:
    platform: linux/amd64
    ports:
      - '6379:6379'
    restart: always
    container_name: redis_service
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "ping" ]
    networks:
      - cloudmart_net
    command: redis-server --requirepass CloudMart123!
  email_sender_service:
    container_name: email_sender_service
    platform: linux/amd64
    environment:
      - Smtp__Host=sandbox.smtp.mailtrap.io
      - Smtp__Port=465
      - Smtp__User=${SMTP_USER}
      - Smtp__Password=${SMTP_PASSWORD}
      - Smtp__FromEmail=no-respond@nexusvault.com
      - Smtp__FromName="Nexus Vault Team"
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=admin
      - RabbitMq__Password=admin123
      - RabbitMq__QueueName=sub-email-sender
      - RabbitMq__ExchangeName=sub-email-sender-exchange
      - RabbitMq__RoutingKeyName=sub-email
  prometheus:
    container_name: prometheus_service
    platform: linux/amd64
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - cloudmart_net
  grafana:
    container_name: grafana_service
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - cloudmart_net

  cloudmart_catalog_db:
    container_name: cloudmart_catalog_db
    platform: linux/amd64
    environment:
      - POSTGRES_USER=catalog
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDB
      - PGDATA=/var/lib/postgresql/data/
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - cloudmart_catalog_db_volumes:/var/lib/postgresql/data/
#  cloudmart.catalog:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_HTTP_PORTS=8080
#      - ASPNETCORE_HTTPS_PORTS=8081
#    ports:
#      - "8080"
#      - "8081"
