# Load automatically definitions (queues, exchanges, bindings)
load_definitions = /etc/rabbitmq/definitions.json

# Good practices for production
loopback_users.guest = false
default_vhost = /

# Logging in console in JSON format
log.console = true
log.console.level = info
log.console.formatter = json
log.file = false


