name: CI Pipeline

on:
  push:
    branches: [ main, develop ]

jobs:

  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore src

      - name: Build
        run: dotnet build src --no-restore --configuration Release

      - name: Run dotnet format
        run: dotnet format src --verbosity d
